# Gitã‚³ãƒãƒ³ãƒ‰ã®ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆã‚’å¢—ã‚„ã™ (ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ: 500ms)
command_timeout = 2000

# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆ
format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$python\
$docker_context\
$time\
$line_break\
$character"""

# å³å´ã®ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆ
right_format = """
$cmd_duration\
$status\
"""

# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®å‰ã«ç©ºè¡Œã‚’å…¥ã‚Œã‚‹
add_newline = true

[custom.separator]
command = "echo ' '"
when = """test "$STARSHIP_NAME" != "" """
style = ""
format = "[$output]($style)"

[directory]
style = "bold fg:#74c7ec"
format = '[$path](bold $style)'
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " "
home_symbol = "ğŸ "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = " "
".config" = " "
"Desktop" = " "
"Movies" = " "
"Applications" = " "

[git_branch]
symbol = " "
style = "bold fg:#a6e3a1"
format = '[$symbol$branch ](bold $style)'
truncation_length = 20
truncation_symbol = "â€¦"

[git_status]
style = "bold fg:#f9e2af"
format = '[$all_status$ahead_behind ](bold $style)'
conflicted = "âœ–"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•${ahead_count}â‡£${behind_count}"
up_to_date = "âœ“"
untracked = "+${count}"
stashed = "âš‘"
modified = "!${count}"
staged = "â—${count}"
renamed = "Â»${count}"
deleted = "âœ˜${count}"

[nodejs]
symbol = "â¬¢"
style = "bold fg:#f5c2e7"
format = '[${symbol}${version} ](bold $style)'

[rust]
symbol = "ğŸ¦€"
style = "bold fg:#f38ba8"
format = '[${symbol}${version} ](bold $style)'

[golang]
symbol = "ğŸ¹"
style = "bold fg:#89dceb"
format = '[${symbol}${version} ](bold $style)'

[python]
symbol = "ğŸ"
style = "bold fg:#f9e2af"
format = '[${symbol}${version} ](bold $style)'

[docker_context]
symbol = "ğŸ³"
style = "bold fg:#89b4fa"
format = '[${symbol}${context} ](bold $style)'

[time]
disabled = false
time_format = "%R"
style = "bold fg:#9399b2"
format = '[$time](bold $style)'

[line_break]
disabled = false

[character]
success_symbol = "[â¯](bold fg:#a6e3a1)"
error_symbol = "[â¯](bold fg:#f38ba8)"
vicmd_symbol = "[â®](bold fg:#f9e2af)"

[status]
style = "bold fg:#f38ba8"
symbol = "ğŸ’« "
format = '[$symbol$status ](bold $style)'
map_symbol = true
disabled = false

[cmd_duration]
min_time = 500
format = '[$duration ](bold $style)'
style = "bold fg:#f5c2e7"
