[tools]
python = "3.12"
ruby = "latest"
node = "20.11.0"
go = "latest"
rust = "latest"
bun = "latest"
deno = "latest"

[settings]
experimental = false
verbose = false

[env]
PYTHONPATH = "${PYTHONPATH:-}:${PWD}"
GEM_HOME = "/Users/esh2n/.gem"
GOPATH = "/Users/esh2n/go"
GOBIN = "/Users/esh2n/go/bin"
CARGO_HOME = "/Users/esh2n/.cargo"
RUSTUP_HOME = "/Users/esh2n/.rustup"
DENO_INSTALL_ROOT = "/Users/esh2n/.deno"
BUN_INSTALL = "/Users/esh2n/.bun"
