[tools]
python = "3.12"
ruby = "latest"
node = "20.11.0"
go = "latest"
rust = "latest"
bun = "latest"
deno = "latest"

[settings]
experimental = false
verbose = false

[env]
PYTHONPATH = "${PYTHONPATH:-}:${PWD}"
GEM_HOME = "/Users/shunya.endo/.gem"
GOPATH = "/Users/shunya.endo/go"
GOBIN = "/Users/shunya.endo/go/bin"
CARGO_HOME = "/Users/shunya.endo/.cargo"
RUSTUP_HOME = "/Users/shunya.endo/.rustup"
DENO_INSTALL_ROOT = "/Users/shunya.endo/.deno"
BUN_INSTALL = "/Users/shunya.endo/.bun"
